version: 2

before:
  hooks:
    - go mod tidy -v
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - 386
      - amd64
      - mips
      - mipsle
      - s390x
      - riscv64
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/naiveswitcher
    binary: naiveswitcher
universal_binaries:
  - name_template: "naiveswitcher"
    replace: false
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "naiveswitcher"
archives:
  - name_template: "naiveswitcher_{{ .Os }}_{{ .Arch }}"
    files:
      # - LICENSE
      - README.md
      # - data
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/ghostgpt/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/ghostgpt/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/ghostgpt/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/ghostgpt/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/ghostgpt/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/ghostgpt/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ghostgpt/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/ghostgpt/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/ghostgpt/{{ .ProjectName }}:latest-amd64
      - ghcr.io/ghostgpt/{{ .ProjectName }}:latest-arm64v8
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
